[package]
name = "terra-rust-script"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"

[workspace]

[dependencies]
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
terra-rust-api = {version ="1.2"}
tokio = { version = "1.4", features = ["full"] }
secp256k1 = { version = "0.20.3", default-features = false }
log="0.4.14"
anyhow="1.0"
serde_json = "1.0.79"
reqwest = { version = "0.11.9"}
base64 = "0.13.0"
base16 = "0.2.1"
async-trait = "0.1.53"